# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d09d1004deee9ef932d91e1d55cb306a"
name = "Icons App"
handle = "icons-app"
application_url = "https://tailbasify-icons-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files, write_products"

[auth]
redirect_urls = ["https://tailbasify-icons-app.vercel.app/auth/callback", "https://tailbasify-icons-app.vercel.app/auth/shopify/callback", "https://tailbasify-icons-app.vercel.app/api/auth/callback"]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Mandatory compliance webhooks for public app distribution
  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[pos]
embedded = false
